---
groups:
  NCSNavigator:
  - staff
  - supervisor
  - User Administrator
users:
  test_user:
    password: test_user
    identifiers:
      staff_id: test_user
    portals:
      - NCSNavigator:
        - Field Staff
    last_name: Usr
    email: t-usr@dev.null
    first_name: T.

  staff_user:
    password: staff_user
    identifiers:
      staff_id: staff_user
    portals:
      - NCSNavigator:
        - Field Staff
    last_name: Usr
    email: staff_user@dev.null
    first_name: staff

  admin_user:
    password: admin_user
    identifiers:
      staff_id: admin_user
    portals:
      - NCSNavigator:
        - User Administrator
    last_name: Usr
    email: admin-usr@dev.null
    first_name: Admin

  specimen_processor:
    password: specimen_processor
    identifiers:
      staff_id: specimen_processor
    portals:
      - NCSNavigator:
        - Specimen Processor
    last_name: Usr
    email: spec_proc@dev.null
    first_name: specimen

  no_portal:
    password: no_portal
    portals: []

  no_roles:
    password: no_roles
    portals:
      - NCSNavigator
